// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbE3FYh5UmFzK-tzonjPFvVo6biq5wvA',
    appId: '1:947085535052:web:ce5d2d96eb5f6eaaa6d1e9',
    messagingSenderId: '947085535052',
    projectId: 'chat-app-6f171',
    authDomain: 'chat-app-6f171.firebaseapp.com',
    storageBucket: 'chat-app-6f171.appspot.com',
    measurementId: 'G-WP56HJ69Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoV8VP5YUIkBJF1TaqTi02Nm5ALnqG4cE',
    appId: '1:947085535052:android:403f9f6dbc35e2dfa6d1e9',
    messagingSenderId: '947085535052',
    projectId: 'chat-app-6f171',
    storageBucket: 'chat-app-6f171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_S-3p6j9abOnUxuH4x1RfY47KFjmEXSg',
    appId: '1:947085535052:ios:842343e737c903b4a6d1e9',
    messagingSenderId: '947085535052',
    projectId: 'chat-app-6f171',
    storageBucket: 'chat-app-6f171.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_S-3p6j9abOnUxuH4x1RfY47KFjmEXSg',
    appId: '1:947085535052:ios:12c99ba1a409a6e4a6d1e9',
    messagingSenderId: '947085535052',
    projectId: 'chat-app-6f171',
    storageBucket: 'chat-app-6f171.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
